package vista;

import controlador.DAO.PedidoDAO;
import controlador.DAO.PersonaDAO;
import controlador.utilidades.UtilidadesControlador;
import modelo.tabla.ExamenTabla;

public class Frm_DetallesPedido extends javax.swing.JFrame {

    private PedidoDAO pedidoDAO;
    private PersonaDAO personaDAO = new PersonaDAO();
    private ExamenTabla examenesTabla = new ExamenTabla();

    public Frm_DetallesPedido() {
        initComponents();
    }
    
    public Frm_DetallesPedido(PedidoDAO pedidoDAO) {
        this.pedidoDAO = pedidoDAO;
        initComponents();
        cargarCampos();
    }

    public void cargarCampos() {
        // Datos Pedido
        lblNroPedido.setText(pedidoDAO.getPedido().getNro_pedido());
        lblFecha.setText(pedidoDAO.getPedido().getFecha_pedido());
        
        // Datos Médico Solicitante
        personaDAO.setPersona(personaDAO.buscarPersonaPorId(pedidoDAO.getPedido().getConsulta().getId_medico()));
        lblMedicoSolicitante.setText(personaDAO.getPersona().toString());
        personaDAO.setPersona(null);
        
        // Datos Paciente
        personaDAO.setPersona(personaDAO.buscarPersonaPorId(pedidoDAO.getPedido().getConsulta().getId_paciente()));
        lblPaciente.setText(personaDAO.getPersona().toString());
        lblSexo.setText(personaDAO.getPersona().getGenero());
        lblFechaNacimiento.setText(personaDAO.getPersona().getFecha_nacimiento());
        lblEdad.setText(String.valueOf(UtilidadesControlador.determinarEdad(personaDAO.getPersona().getFecha_nacimiento())));
        lblDireccion.setText(personaDAO.getPersona().getDireccion());
        
        personaDAO.setPersona(null);
        
        cargarTabla();
    }

    public void cargarTabla() {
        examenesTabla.setListaExamenes(pedidoDAO.getPedido().getListaExamen());
        tblExamenes.setModel(examenesTabla);
        tblExamenes.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMedicoSolicitante = new javax.swing.JLabel();
        lblNroPedido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExamenes = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel1.setText("Nro de Pedido:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 20, 100, 16);

        jLabel2.setText("Médico solicitante:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 120, 16);

        lblMedicoSolicitante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblMedicoSolicitante);
        lblMedicoSolicitante.setBounds(150, 60, 430, 20);

        lblNroPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblNroPedido);
        lblNroPedido.setBounds(150, 20, 130, 20);

        jLabel3.setText("Fecha:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(350, 20, 50, 16);

        lblFecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblFecha);
        lblFecha.setBounds(410, 20, 170, 20);

        lblPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblPaciente);
        lblPaciente.setBounds(150, 100, 430, 20);

        jLabel4.setText("Paciente:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 110, 16);

        lblDireccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblDireccion);
        lblDireccion.setBounds(150, 140, 430, 20);

        jLabel5.setText("Dirección:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 140, 110, 16);

        jLabel6.setText("Sexo:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 180, 40, 16);

        lblSexo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblSexo);
        lblSexo.setBounds(80, 180, 60, 20);

        lblFechaNacimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblFechaNacimiento);
        lblFechaNacimiento.setBounds(300, 180, 130, 20);

        jLabel7.setText("Fecha de Nacimiento:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(160, 180, 130, 16);

        lblEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(lblEdad);
        lblEdad.setBounds(510, 180, 70, 20);

        jLabel8.setText("Edad:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(450, 180, 40, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 600, 220);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        tblExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblExamenes);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(12, 12, 570, 210);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 240, 600, 240);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver);
        btnVolver.setBounds(10, 490, 80, 29);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(634, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_DetallesPedido.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_DetallesPedido.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_DetallesPedido.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_DetallesPedido.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_DetallesPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblMedicoSolicitante;
    private javax.swing.JLabel lblNroPedido;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTable tblExamenes;
    // End of variables declaration//GEN-END:variables
}
