package vista;

import controlador.DAO.DiagnosticoDAO;
import controlador.DAO.HistorialClinicoDAO;
import controlador.DAO.PersonaDAO;
import javax.swing.JOptionPane;
import modelo.HistorialClinico;
import modelo.tabla.HCDiagnosticoTabla;
import modelo.tabla.HistorialClinicoTabla;

public class historial_clinico extends javax.swing.JFrame {

    HistorialClinicoDAO hcDAO = new HistorialClinicoDAO();
    PersonaDAO personaDAO = new PersonaDAO();
    DiagnosticoDAO dDAO = new DiagnosticoDAO();
    
    HCDiagnosticoTabla hcdt = new HCDiagnosticoTabla();
    HistorialClinicoTabla mhc = new HistorialClinicoTabla();
    
    Long idPersona;
    public historial_clinico() {
        initComponents();
    }
    
    public historial_clinico(Long idPersona) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        this.idPersona = idPersona;
        bloquearDatosPersona();
        bloquearDatosHC();
        cargarTabla();
        cargarPersona();
        cargarTablaDiagnosticos();
    }

    public void limpiar(){
    txt_Habito.setText("");
    txt_tipoSangre.setText("");
    txt_enfermedad.setText("");
    }
    public void bloquearDatosPersona() {
        txt_apellido.setEnabled(false);
        txt_cedula.setEnabled(false);
        txt_nombre.setEnabled(false);
    }

    public void bloquearDatosHC() {
        txt_Habito.setEnabled(false);
        txt_enfermedad.setEnabled(false);
        txt_tipoSangre.setEnabled(false);
        cbx_parentezco.setEnabled(false);
        btn_agregarTS_H.setEnabled(false);
        btn_cancelar.setEnabled(false);
    }

    public void desbloquearDatosHC() {
        txt_Habito.setEnabled(true);
        txt_enfermedad.setEnabled(true);
        txt_tipoSangre.setEnabled(true);
        cbx_parentezco.setEnabled(true);
        btn_agregarTS_H.setEnabled(true);
        btn_cancelar.setEnabled(true);
    }

    public void cargarTabla() {
        mhc.setListaHC(hcDAO.TodosHistorialClinico());
        tbl_HC.setModel(mhc);
        tbl_HC.updateUI();
    }
    
    public void cargarTablaDiagnosticos() {
        hcdt.setListaDiagnosticos(dDAO.diagnosticoPorPersona(idPersona)); // cambiar por variable global
        tbl_diagnosticos.setModel(hcdt);
        tbl_diagnosticos.updateUI();
    }

    public void cargarPersona() {
        personaDAO.setPersona(null);
        personaDAO.setPersona(personaDAO.buscarPersonaPorId(idPersona));// cambiar por variable global
        txt_nombre.setText(personaDAO.getPersona().getNombre());
        txt_apellido.setText(personaDAO.getPersona().getApellido());
        txt_cedula.setText(personaDAO.getPersona().getCedula());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_hc = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_diagnosticos = new javax.swing.JTable();
        btn_verDetalle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tipoSangre = new javax.swing.JTextField();
        txt_Habito = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_HC = new javax.swing.JTable();
        btn_agregarTS_H = new javax.swing.JButton();
        btn_editarTS_H = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cbx_parentezco = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txt_enfermedad = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial Clínico");

        panel_hc.setBackground(new java.awt.Color(153, 204, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        jLabel15.setText("Cédula:");

        jLabel16.setText("Nombre:");

        jLabel17.setText("Apellido:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(25, 25, 25)
                        .addComponent(txt_cedula)
                        .addGap(392, 392, 392))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_apellido)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Diagnósticos"));

        tbl_diagnosticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Medico", "Enfermedad"
            }
        ));
        jScrollPane2.setViewportView(tbl_diagnosticos);

        btn_verDetalle.setText("Ver Detalle");
        btn_verDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_verDetalle))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_verDetalle)
                .addGap(206, 206, 206))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Sangre , Habito y Enfermedades Hereditarias"));

        jLabel1.setText("Tipo de Sangre:");

        jLabel2.setText("Habito:");

        tbl_HC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "parentezco", "enfermedad hereditaria", "Tipo de Sangre", "Habito"
            }
        ));
        tbl_HC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HCMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_HC);

        btn_agregarTS_H.setText("Agregar");
        btn_agregarTS_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarTS_HActionPerformed(evt);
            }
        });

        btn_editarTS_H.setText("Editar");
        btn_editarTS_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarTS_HActionPerformed(evt);
            }
        });

        jLabel13.setText("Parentezco:");

        cbx_parentezco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padre", "Madre" }));

        jLabel14.setText("Enfermedad:");

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_nuevo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_editarTS_H, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(142, 142, 142))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(cbx_parentezco, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)
                            .addComponent(jLabel14)
                            .addGap(18, 18, 18)
                            .addComponent(txt_enfermedad))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_tipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Habito, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_agregarTS_H, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_tipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_agregarTS_H))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_Habito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbx_parentezco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_enfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editarTS_H)
                    .addComponent(btn_nuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_hcLayout = new javax.swing.GroupLayout(panel_hc);
        panel_hc.setLayout(panel_hcLayout);
        panel_hcLayout.setHorizontalGroup(
            panel_hcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_hcLayout.createSequentialGroup()
                .addGroup(panel_hcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_hcLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_hcLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_hcLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_hcLayout.setVerticalGroup(
            panel_hcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_hcLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel_hc, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verDetalleActionPerformed
        if (tbl_diagnosticos.getSelectedRow() != - 1) {
            dDAO.setDiagnostico(null);
            dDAO.setDiagnostico(dDAO.diagnosticoPorPersona(idPersona).get(tbl_diagnosticos.getSelectedRow()));
            new Frm_Detalle_Diagnostico(dDAO).setVisible(true);
            dDAO.setDiagnostico(null);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, primero seleccione un pedido de la tabla");
        }     
    }//GEN-LAST:event_btn_verDetalleActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        desbloquearDatosHC();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_agregarTS_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarTS_HActionPerformed

        hcDAO.setHc(null);

        hcDAO.getHc().setTipo_sangre(txt_tipoSangre.getText());

        hcDAO.getHc().setEnfermedad_hereditaria(String.valueOf(cbx_parentezco.getSelectedItem()  +"-"+ txt_enfermedad.getText()));
        hcDAO.getHc().setHabitos(txt_Habito.getText());

        //agregar persona
        personaDAO.setPersona(null);
        personaDAO.setPersona(personaDAO.buscarPersonaPorId(idPersona)); // cambiar por variable global
        hcDAO.getHc().setPersona(personaDAO.getPersona());

        hcDAO.setHc(hcDAO.getHc());
        hcDAO.agregarHC(hcDAO.getHc());
        cargarTabla();
       limpiar();
        bloquearDatosHC();

    }//GEN-LAST:event_btn_agregarTS_HActionPerformed

    private void btn_editarTS_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarTS_HActionPerformed
        int fila = tbl_HC.getSelectedRow();
        if (fila != -1) {

            hcDAO.setHc(null);
            hcDAO.setHc((HistorialClinico)hcDAO.TodosHistorialClinico().get(fila));
            //hcDAO.setHc(exam);
            hcDAO.getHc().setId_historial_clinico(hcDAO.getHc().getId_historial_clinico());
            hcDAO.getHc().setTipo_sangre(txt_tipoSangre.getText());

            hcDAO.getHc().setEnfermedad_hereditaria(String.valueOf(cbx_parentezco.getSelectedItem() +"-"+ txt_enfermedad.getText()));
            hcDAO.getHc().setHabitos(txt_Habito.getText());

                //agregar persona
               personaDAO.setPersona(null);
               personaDAO.setPersona(personaDAO.buscarPersonaPorId(idPersona)); // cambiar por variable global
            hcDAO.getHc().setPersona(personaDAO.getPersona());

            hcDAO.setHc(hcDAO.getHc());
            hcDAO.editarHC(hcDAO.getHc());
            cargarTabla();
            limpiar();
            bloquearDatosHC();

            tbl_HC.removeRowSelectionInterval(0, tbl_HC.getRowCount() - 1);
        } else {
            JOptionPane.showMessageDialog(rootPane, "debe seleccionar una fila de la tabla");
        }
    }//GEN-LAST:event_btn_editarTS_HActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        bloquearDatosHC();
        limpiar();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void tbl_HCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HCMouseClicked
        int fila = tbl_HC.getSelectedRow();
       
        desbloquearDatosHC();
        String tipoSangre = String.valueOf(tbl_HC.getValueAt(fila, 0));
        String parentezco = String.valueOf(tbl_HC.getValueAt(fila, 1));
        String enfermedad = String.valueOf(tbl_HC.getValueAt(fila, 2));
        String habito = String.valueOf(tbl_HC.getValueAt(fila, 3));

        txt_tipoSangre.setText(tipoSangre);
        txt_enfermedad.setText(enfermedad);
        txt_Habito.setText(habito);

        if (parentezco.equalsIgnoreCase("padre")) {
            cbx_parentezco.setSelectedIndex(0);
        } else {
            cbx_parentezco.setSelectedIndex(1);
        }
       
    }//GEN-LAST:event_tbl_HCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(historial_clinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(historial_clinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(historial_clinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(historial_clinico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new historial_clinico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarTS_H;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editarTS_H;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_verDetalle;
    private javax.swing.JComboBox<String> cbx_parentezco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel_hc;
    private javax.swing.JTable tbl_HC;
    private javax.swing.JTable tbl_diagnosticos;
    private javax.swing.JTextField txt_Habito;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_enfermedad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_tipoSangre;
    // End of variables declaration//GEN-END:variables
}
